### ISSUE TITLE
Support for backend schema representation

### ISSUE THREAD

**Issue by beanaroo** [hashicorp/terraform-json#11]
The provider schema json is immensely useful for working with plan wrapping, generation and validation/testing, so I'll start the issue off with a big thank you!

A plan file also includes the `terraform` block which containe `required_version` and `backend`. Is it possible to include these in the representation? Or are they already available elsewhere?

From the repository README, I presumed this would be the appropriate place to submit the enhancement.

**Comment by beanaroo** [comment]
Linking https://github.com/hashicorp/terraform/issues/21025 as suggested by @vancluever

**Comment by radeksimko** [comment]
Generally this repo tends to follow changes in upstream Terraform repo closely - so I don't think it's necessary to keep this issue open here as it is not actionable from here.

As already mentioned this isn't addressable without Terraform exposing backend schema first.

Thank you for the interest and for linking the upstream issue.
