### ISSUE TITLE
Support Conflicting Attributes

### ISSUE THREAD

**Issue by beanaroo** [hashicorp/terraform-json#16]
Some attributes conflict and are mutually exclusive. It would be great if the schema could include a `conflicts` field.

For example, `aws_rds_cluster_instance` has either `identifier` or `identifier_prefix` but not both.

Similar rules apply to `aws_route_table.route` destinations.

**Comment by vancluever** [comment]
Hey @beanaroo, this is probably better suited to go in the Terraform Core issue tracker, this is simply just a de-coupled JSON representation Go helper. Once the support is added into Terraform Core it can be updated here.

I'll keep this open for now but can you add this issue over there and maybe link it back here?

Thanks!

**Comment by radeksimko** [comment]
Generally this repo tends to follow changes in upstream Terraform repo closely - so I don't think it's necessary to keep this issue open here as it is not actionable from here.

However I am sure that the SDK team would be happy to talk about such request in https://github.com/hashicorp/terraform-plugin-sdk

When the change makes its way into an SDK release, the protocol and Terraform itself, we'd be happy to add it to `terraform-json`.
