### ISSUE TITLE
Add support for protocol v6 schema changes

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform-json#27]
i.e. reflect https://github.com/hashicorp/terraform/pull/28055

**Comment by vancluever** [comment]
@radeksimko do we have any sort of high-level detail on what needs to happen here versus having to dig through the PR?

**Comment by radeksimko** [comment]
Sorry for the initial brief description 😅 
I don't have much more detail as there AFAIK isn't any public docs about it either.

I was planning to go through the linked PR myself to understand the full impact and raise a PR here - I just created this issue mostly as a reminder.
