### ISSUE TITLE
feat: add Default to SchemaAttribute

### ISSUE THREAD

**Issue by mavogel** [hashicorp/terraform-json#35]
link https://github.com/hashicorp/terraform-plugin-docs/issues/65

**Comment by radeksimko** [comment]
👋🏻   Manuel,
This library is only responsible for representing the JSON output from terraform, in this case from `terraform providers schema -json`.

I agree it would be useful for docs generation (and other use cases) to have some access to "default" value. However this would first have to be implemented in

- TF Core: https://github.com/hashicorp/terraform/blob/4b25a07bc796c392e95ce9d8b4228e6b3416803b/command/jsonprovider/attribute.go#L10-L20
- the gRPC protocol (used to exchange data between providers and core; via SDK): https://github.com/hashicorp/terraform/blob/4b25a07bc796c392e95ce9d8b4228e6b3416803b/docs/plugin-protocol/tfplugin6.0.proto#L90-L101
- the [plugin SDK](https://github.com/hashicorp/terraform-plugin-sdk); or more specifically in `terraform-plugin-go` library which provides the protocol abstraction layer: https://github.com/hashicorp/terraform-plugin-go/blob/26c9b682270fc6618969eccbd21789a48c1d8251/tfprotov6/internal/tfplugin6/tfplugin6.proto#L90-L101

This may or may not be a simple change, but discussion needs to happen about such a change between all affected projects. The best place to start may be by filing an issue in TF Core or SDK.

**Comment by mavogel** [comment]
Thanks, Radek for the detailed explanation :) I did not know this requires touching so many other parts. For now, I can live with manually adding/copy-pasting the string to the `Description` to the schema until this is implemented

**Comment by radeksimko** [comment]
Human representation of more complex `cty.Value`s is one problem to solve, although not necessarily a hard one.

Either way if you end up doing something manually it would be still useful to [open the issue in TF Core](https://github.com/hashicorp/terraform/issues/new/choose) and mention the use cases + how you solve it today. That way we can be sure that any future changes solve your use case well.

Generally we (maintainers of `terraform-json` tend to follow the changelog of TF Core and reflect new changes here fairly frequently, so I'm going to close this issue as it's not actionable here in this context, but happy to add it once it is supported.
