### ISSUE TITLE
Include moved results from the plan output

### ISSUE THREAD

**Issue by jbardin** [hashicorp/terraform-json#45]
Terraform v1.1 will include support for configuration based refactoring, starting with `moved` blocks to change the address of resources in the configuration and state. This is exposed in the plan output by the addition of a `previous_address` field in the `resource_changes` objects: https://github.com/hashicorp/terraform/pull/29603

**Comment by takaishi** [comment]
Hello, I created Pull Request to add PreviousAddress to ResourceChange https://github.com/hashicorp/terraform-json/pull/95 .
Could anyone review it?

**Comment by liamcervante** [comment]
Merged #95 so closing this. Thanks @takaishi!
