### ISSUE TITLE
Plan struct is missing ResourceDrift

### ISSUE THREAD

**Issue by jsenich-r7** [hashicorp/terraform-json#47]
The `Plan` struct is missing the `ResourceDrift` field for modeling the newer `resource_drift` section in the plan json output.

**Comment by radeksimko** [comment]
Good catch, thanks for opening the issue!

It looks like this was not yet released as part of a stable release though https://github.com/hashicorp/terraform/commit/3c8a4e6e05afefb7639bf30efa852cf59f14ade6
This also explains why this is not yet documented on the website: https://www.terraform.io/docs/internals/json-format.html#plan-representation

I will need to double check with the core team internally on the expectations wrt stability, or more specifically `1.1.0`.

**Comment by radeksimko** [comment]
Actually it was pointed out to me that this was part of 0.15 release already, I just misread the git log.

**Comment by stigok** [comment]
Do you know any ways to determine drifted resources changes from other resource changes using this library? Would be nice to find a work-around while waiting for this.

**Comment by radeksimko** [comment]
This was implemented as part of https://github.com/hashicorp/terraform-json/pull/73
