### ISSUE TITLE
Adding MarkdownDescription as part of the schema json

### ISSUE THREAD

**Issue by jkroepke** [hashicorp/terraform-json#82]
The Terraform Plugin SDK allows to declare the documentation for end-users inside the code itself.

Example: https://github.com/hashicorp/terraform-provider-scaffolding-framework/blob/abeef77b77014d6d83e72834c44ea8c19bc971e5/internal/provider/provider.go#L39

Extending the Terraform Schema JSON with the end-user documentation has a huge benefit of the eco system behind terraform. For example, Editor that relies on the Terraform Schema JSON, could display in-line documentation of resources and attributes.

I may recommend to add a toggle to `terraform provider -json` command. Since including the documentation would increase the JSON size to some Megabytes. It should be only a part of it, if its requested (opt-in)

**Comment by radeksimko** [comment]
Hi @jkroepke 
This is already part of the mentioned CLI command and also part of `terraform-json`.

https://github.com/hashicorp/terraform-json/blob/4b583933ed58b10b98e57f810ca8603d8afdc2b2/schemas.go#L121-L124

https://github.com/hashicorp/terraform-json/blob/4b583933ed58b10b98e57f810ca8603d8afdc2b2/schemas.go#L202-L205

Let us know if there's something else missing.
